# Full schema defined in /src/theticketbot/config.py

[bot]
token = ""
extensions = [
    ".cogs.cleanup",
    ".cogs.errors",
    ".cogs.inbox",
    ".cogs.owner",
    ".cogs.select",
]
allow_jishaku = true

[bot.inbox]
max_attachment_size = 5000000

[bot.intents]
# https://discordpy.readthedocs.io/en/stable/api.html#intents
# All default intents are enabled but can be modified here
guild_messages = true
guilds = true
members = true
message_content = true

auto_moderation = false
auto_moderation_configuration = false
auto_moderation_execution = false
dm_messages = false
dm_reactions = false
dm_typing = false
emojis_and_stickers = false
guild_scheduled_events = false
guild_reactions = false
guild_typing = false
integrations = false
invites = false
moderation = false
presences = false
voice_states = false
webhooks = false

[db]
path = "data/theticketbot.db"
