# Full schema defined in /src/theticketbot/config.py

[bot]
token = ""
extensions = [
    ".cogs.cleanup",
    ".cogs.errors",
    ".cogs.inbox",
    ".cogs.owner",
    ".cogs.select",
]
allow_jishaku = true

[bot.inbox]
max_attachment_size = 5000000

[bot.intents]
# https://discordpy.readthedocs.io/en/stable/api.html#intents
guild_messages = true
guilds = true
members = true

auto_moderation_configuration = false
auto_moderation_execution = false
dm_messages = false
dm_polls = false
dm_reactions = false
dm_typing = false
emojis_and_stickers = false
guild_polls = false
guild_reactions = false
guild_scheduled_events = false
guild_typing = false
integrations = false
invites = false
message_content = false
moderation = false
presences = false
voice_states = false
webhooks = false

[db]
path = "${USER_DATA_DIR}/theticketbot.db"
pragmas = []
key_template = ""
